### ISSUE TITLE
Missing notifications

### ISSUE THREAD

**Issue by 7heo** [almindor/harbour-jTox#4]
The application cover displays how many messages have been received since last time the user checked, but there is no notification in the phone UI, or LED color change.

**Comment by almindor** [comment]
UI notifies of new messages by showing the friend's name bold in friends view and showing new messages bold in message view (which switch to normal after 2 seconds).

I'll keep the issue open tho since I didn't do the LED color change yet.

**Comment by 7heo** [comment]
Also, there is no audio notification AFAICT.

**Comment by almindor** [comment]
Yes this is another issue I'm aware of. I expected the nemo notifications to play sounds because Jolla doesn't seem to make the QML Notification object show the "hints" property which can be used to add a "sound-name" for the notification. I might need to switch to the C++ one or just play a sound directly when the event happens.

**Comment by almindor** [comment]
This was actually fixed in 1.0.1 I couldn't get LED to change color or blink tho, so I'll open a new issue for that. Audio is now played on messages.
